version: '3.8'

services:
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge